using System.IO;
using System.Threading.Tasks;
using Syncro.Desktop.Services.SyncroCLI.Execution;

namespace Syncro.Desktop.Services.SyncroCLI.Providers
{
    public class MernProvider : IProjectProvider
    {
        private readonly ProcessRunner _runner;

        public MernProvider(ProcessRunner runner)
        {
            _runner = runner;
        }

        public string StackName => "mern";

        public async Task<bool> Create(string name, string targetPath)
        {
            try
            {
                string projectDir = Path.Combine(targetPath, name);
                if (!Directory.Exists(projectDir)) Directory.CreateDirectory(projectDir);

                // Server setup
                string serverDir = Path.Combine(projectDir, "server");
                Directory.CreateDirectory(serverDir);
                await _runner.Run("npm init -y", serverDir);
                await _runner.Run("npm install express mongoose dotenv cors", serverDir);

                // Client setup (using Vite for speed)
                await _runner.Run($"npm create vite@latest client -- --template react", projectDir);
                await _runner.Run("npm install", Path.Combine(projectDir, "client"));

                await File.WriteAllTextAsync(Path.Combine(projectDir, "README.md"), $"# {name}\nGenerated by SyncroCLI");
                return true;
            }
            catch { return false; }
        }
    }
}
