import '../core/file_writer.dart';
import '../core/models.dart';
import 'base_generator.dart';

class ApiGenerator implements BaseGenerator {
  @override
  Future<void> generate(AppModel model) async {
    final apiConfig = model.datasource;
    final baseUrl = apiConfig['base_url'] ?? 'https://api.thunder.app';
    
    final code = """
import 'dart:convert';
import 'package:http/http.dart' as http;

/// Production-grade API Service generated by Thunder Engine.
/// Handles HTTP communication, JSON encoding/decoding, and error management.
class ApiService {
  final String baseUrl;
  final Map<String, String> defaultHeaders;

  ApiService({
    required this.baseUrl, 
    this.defaultHeaders = const {'Content-Type': 'application/json'},
  });

  /// Performs a GET request to the specified [endpoint].
  Future<Map<String, dynamic>> get(String endpoint) async {
    try {
      final response = await http.get(
        Uri.parse('\$baseUrl\$endpoint'),
        headers: defaultHeaders,
      );

      return _handleResponse(response);
    } catch (e) {
      throw Exception('Thunder API [GET] Failed: \$e');
    }
  }

  /// Performs a POST request to the specified [endpoint] with [body].
  Future<Map<String, dynamic>> post(String endpoint, Map<String, dynamic> body) async {
    try {
      final response = await http.post(
        Uri.parse('\$baseUrl\$endpoint'),
        headers: defaultHeaders,
        body: jsonEncode(body),
      );

      return _handleResponse(response);
    } catch (e) {
      throw Exception('Thunder API [POST] Failed: \$e');
    }
  }

  /// Performs a PUT request to the specified [endpoint] with [body].
  Future<Map<String, dynamic>> put(String endpoint, Map<String, dynamic> body) async {
    try {
      final response = await http.put(
        Uri.parse('\$baseUrl\$endpoint'),
        headers: defaultHeaders,
        body: jsonEncode(body),
      );

      return _handleResponse(response);
    } catch (e) {
      throw Exception('Thunder API [PUT] Failed: \$e');
    }
  }

  /// Performs a DELETE request to the specified [endpoint].
  Future<Map<String, dynamic>> delete(String endpoint) async {
    try {
      final response = await http.delete(
        Uri.parse('\$baseUrl\$endpoint'),
        headers: defaultHeaders,
      );

      return _handleResponse(response);
    } catch (e) {
      throw Exception('Thunder API [DELETE] Failed: \$e');
    }
  }

  Map<String, dynamic> _handleResponse(http.Response response) {
    if (response.statusCode >= 200 && response.statusCode < 300) {
      if (response.body.isEmpty) return {};
      return jsonDecode(response.body);
    } else {
      throw Exception('Thunder API Error [\${response.statusCode}]: \${response.body}');
    }
  }
}
""";
    FileWriter.write('lib_gen/core/services/api_service.dart', code);
  }
}
