import '../core/dependency_graph.dart';
import '../core/file_writer.dart';
import '../core/models.dart';
import '../utils/string_utils.dart';
import 'base_generator.dart';

class RepositoryGenerator implements BaseGenerator {
  DependencyGraph? graph;

  @override
  Future<void> generate(AppModel model) async {
    final dg = graph ?? DependencyGraph()..resolve(model);

    for (var feature in dg.allFeatures) {
      final className = StringUtils.toPascalCase(feature);
      _generateRepository(feature, className, model);
    }
  }

  void _generateRepository(String feature, String className, AppModel model) {
    final repoConfig = model.repository[feature];
    final List<String> apis = (repoConfig?['apis'] as List?)?.cast<String>() ?? [];
    
    final methodBuffer = StringBuffer();

    for (var apiName in apis) {
      final apiDef = model.api['api']?[apiName];
      if (apiDef == null) continue;

      final method = (apiDef['method'] as String).toLowerCase();
      final endpoint = apiDef['endpoint'] as String;
      final methodName = apiName;

      if (method == 'get') {
        methodBuffer.writeln("""
  Future<Map<String, dynamic>> $methodName() async {
    return await api.get('$endpoint');
  }""");
      } else if (method == 'post') {
        methodBuffer.writeln("""
  Future<Map<String, dynamic>> $methodName(Map<String, dynamic> data) async {
    return await api.post('$endpoint', data);
  }""");
      }
    }

    // Default method if none defined
    if (methodBuffer.isEmpty) {
      methodBuffer.writeln("""
  Future<Map<String, dynamic>> getData() async {
    return await api.get('/$feature');
  }""");
    }

    final code = """
import '../../../core/services/api_service.dart';
import '../../../core/services/db_service.dart';

/// Repository for $className generated by Thunder Engine.
/// Orchestrates data flow between ApiService and DbService.
class ${className}Repository {
  final ApiService api;
  final DbService db;

  ${className}Repository(this.api, this.db);

${methodBuffer.toString()}
}
""";
    FileWriter.write('lib_gen/features/$feature/repository/${feature}_repository.dart', code);
  }
}
