using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Syncro.Desktop.Services.projectgenerator.Registry;

namespace Syncro.Desktop.Services.projectgenerator.Orchestration
{
    public class ProjectWiringService
    {
        public Task WireProjectAsync(StackArchetype stack, string projectPath, int assignedPort, int? apiPort)
        {
            if (stack.Kind == StackKind.Frontend && apiPort.HasValue)
            {
                // Write environment file pointing to the backend
                string envFile = Path.Combine(projectPath, ".env.local");
                string content = $"# Auto-generated by Syncro\n";
                
                if (stack.Id == "nextjs")
                {
                    content += $"NEXT_PUBLIC_API_URL=http://localhost:{apiPort}\n";
                }
                else if (stack.Id == "vite-react")
                {
                    content += $"VITE_API_URL=http://localhost:{apiPort}\n";
                }
                else
                {
                    content += $"API_URL=http://localhost:{apiPort}\n";
                }

                File.WriteAllText(envFile, content);
            }

            return Task.CompletedTask;
        }
    }
}
