using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Syncro.Desktop.Services.Database
{
    /// <summary>An application service (frontend/backend) to include in the compose stack.</summary>
    public record AppServiceSpec(
        string Name,
        string BuildContext,                       // path relative to compose file
        int HostPort,
        int ContainerPort,
        IReadOnlyDictionary<string, string>? Env = null,
        IReadOnlyList<string>? DependsOn = null);   // service names to wait on (service_healthy)

    /// <summary>
    /// Emits a <c>docker-compose.yml</c> (DB services from <see cref="DatabaseScaffolder"/> + optional
    /// app services) plus cross-platform run scripts. Part of solving projectgenerator.md bug B7 and
    /// the deploy story in engine/optimisation server cli.md §3.3.
    /// </summary>
    public class ComposeGenerator
    {
        /// <summary>Build the compose file text. Returns "" when nothing needs Docker (e.g. SQLite-only).</summary>
        public string Build(string stackName, IEnumerable<DbProvisionResult> dbs, IEnumerable<AppServiceSpec>? apps = null)
        {
            var dbList = dbs?.Where(d => d.RequiresDocker && !string.IsNullOrWhiteSpace(d.ComposeServiceYaml)).ToList()
                         ?? new List<DbProvisionResult>();
            var appList = apps?.ToList() ?? new List<AppServiceSpec>();
            if (dbList.Count == 0 && appList.Count == 0) return "";

            var net = $"{Slug(stackName)}_net";
            var sb = new StringBuilder();
            sb.AppendLine($"# docker-compose.yml — generated by Syncro for '{stackName}'");
            sb.AppendLine("services:");

            foreach (var db in dbList)
                sb.Append(db.ComposeServiceYaml.TrimEnd('\n')).AppendLine().AppendLine();

            foreach (var app in appList)
                sb.Append(AppServiceBlock(app)).AppendLine();

            var volumes = dbList.SelectMany(d => d.Volumes).Distinct().ToList();
            if (volumes.Count > 0)
            {
                sb.AppendLine("volumes:");
                foreach (var v in volumes) sb.AppendLine($"  {v}:");
                sb.AppendLine();
            }

            sb.AppendLine("networks:");
            sb.AppendLine("  default:");
            sb.AppendLine($"    name: {net}");
            return sb.ToString();
        }

        /// <summary>Write docker-compose.yml + up/down scripts into <paramref name="targetPath"/>.</summary>
        public async Task<bool> WriteAsync(string targetPath, string stackName,
            IEnumerable<DbProvisionResult> dbs, IEnumerable<AppServiceSpec>? apps = null,
            Action<string>? onLog = null, CancellationToken ct = default)
        {
            try
            {
                Directory.CreateDirectory(targetPath);
                var compose = Build(stackName, dbs, apps);

                if (string.IsNullOrEmpty(compose))
                {
                    onLog?.Invoke("[compose] No Docker services required (SQLite/embedded) — skipping compose.");
                    return false;
                }

                var composePath = Path.Combine(targetPath, "docker-compose.yml");
                await File.WriteAllTextAsync(composePath, compose, ct);
                onLog?.Invoke($"[compose] wrote {composePath}");

                await WriteRunScriptsAsync(targetPath, stackName, ct);
                onLog?.Invoke("[compose] wrote up/down scripts (up.sh · up.bat · down.sh · down.bat)");
                return true;
            }
            catch (Exception ex)
            {
                onLog?.Invoke($"[compose ERROR] {ex.Message}");
                return false;
            }
        }

        private static string AppServiceBlock(AppServiceSpec app)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"  {app.Name}:");
            sb.AppendLine($"    build: {app.BuildContext}");
            sb.AppendLine("    restart: unless-stopped");
            sb.AppendLine("    ports:");
            sb.AppendLine($"      - \"{app.HostPort}:{app.ContainerPort}\"");
            if (app.Env is { Count: > 0 })
            {
                sb.AppendLine("    environment:");
                foreach (var (k, v) in app.Env) sb.AppendLine($"      {k}: {v}");
            }
            if (app.DependsOn is { Count: > 0 })
            {
                sb.AppendLine("    depends_on:");
                foreach (var dep in app.DependsOn)
                {
                    sb.AppendLine($"      {dep}:");
                    sb.AppendLine("        condition: service_healthy");
                }
            }
            return sb.ToString();
        }

        private static async Task WriteRunScriptsAsync(string path, string stackName, CancellationToken ct)
        {
            await File.WriteAllTextAsync(Path.Combine(path, "up.sh"),
$@"#!/usr/bin/env bash
set -e
cd ""$(dirname ""$0"")""
echo ""Starting {stackName} services…""
docker compose up -d
docker compose ps
", ct);

            await File.WriteAllTextAsync(Path.Combine(path, "up.bat"),
$@"@echo off
cd /d ""%~dp0""
echo Starting {stackName} services...
docker compose up -d
docker compose ps
", ct);

            await File.WriteAllTextAsync(Path.Combine(path, "down.sh"),
@"#!/usr/bin/env bash
cd ""$(dirname ""$0"")""
docker compose down
", ct);

            await File.WriteAllTextAsync(Path.Combine(path, "down.bat"),
@"@echo off
cd /d ""%~dp0""
docker compose down
", ct);
        }

        private static string Slug(string s) =>
            new string((s ?? "stack").ToLowerInvariant().Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray()).Trim('_');
    }
}
