using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Syncro.Desktop.Services.Database
{
    public enum DbEngine { Postgres, Mysql, Mongo, Redis, Sqlite }

    /// <summary>What database a project wants. Port/user/password are optional — sensible dev
    /// defaults are filled in (the port broker overrides <see cref="Port"/> to avoid collisions).</summary>
    public record DbRequest(DbEngine Engine, string? Name = null, int? Port = null,
                            string? User = null, string? Password = null);

    /// <summary>The provisioned database: how to connect, what to inject into dependents, and the
    /// docker-compose service block to emit.</summary>
    public record DbProvisionResult(
        DbEngine Engine,
        string ServiceName,                        // compose service + in-network DNS host
        int HostPort,
        string ConnectionString,                   // in-network (host = ServiceName)
        string HostConnectionString,               // localhost:HostPort (host tools)
        IReadOnlyDictionary<string, string> EnvVars,  // DATABASE_URL, etc. — inject into the backend
        string ComposeServiceYaml,                 // 2-space-indented block, or "" for embedded (sqlite)
        IReadOnlyList<string> Volumes,             // named volumes to declare
        bool RequiresDocker);

    /// <summary>
    /// The database archetype (solves projectgenerator.md bug B7 — "no database archetype").
    /// Turns a <see cref="DbRequest"/> into connection strings, env vars for the backend, and a
    /// docker-compose service block (or a file-based SQLite fallback that needs no Docker).
    /// See engine/optimisation server cli.md §3.3.
    /// </summary>
    public class DatabaseScaffolder
    {
        public DbProvisionResult Provision(DbRequest req)
        {
            var name = Sanitize(req.Name);
            var user = string.IsNullOrWhiteSpace(req.User) ? "syncro" : req.User!;
            var pass = string.IsNullOrWhiteSpace(req.Password) ? "syncro_dev_pw" : req.Password!;

            return req.Engine switch
            {
                DbEngine.Postgres => Postgres(name, user, pass, req.Port ?? 5432),
                DbEngine.Mysql => Mysql(name, user, pass, req.Port ?? 3306),
                DbEngine.Mongo => Mongo(name, user, pass, req.Port ?? 27017),
                DbEngine.Redis => Redis(req.Port ?? 6379),
                DbEngine.Sqlite => Sqlite(name),
                _ => throw new ArgumentOutOfRangeException(nameof(req.Engine))
            };
        }

        /// <summary>Write the backend env vars (DATABASE_URL, …) as a <c>.env</c> fragment.</summary>
        public async Task WriteEnvAsync(string targetPath, DbProvisionResult db,
                                        Action<string>? onLog = null, CancellationToken ct = default)
        {
            Directory.CreateDirectory(targetPath);
            var envPath = Path.Combine(targetPath, ".env");
            var sb = new StringBuilder();
            sb.AppendLine("# Generated by Syncro — database connection");
            foreach (var (k, v) in db.EnvVars) sb.AppendLine($"{k}={v}");
            await File.AppendAllTextAsync(envPath, sb.ToString(), ct);
            onLog?.Invoke($"[DB] wrote {db.EnvVars.Count} env var(s) to {envPath}");
        }

        // ── Engines ──────────────────────────────────────────────────────

        private static DbProvisionResult Postgres(string db, string user, string pass, int port)
        {
            const string svc = "postgres";
            var conn = $"postgresql://{user}:{pass}@{svc}:5432/{db}";
            var host = $"postgresql://{user}:{pass}@localhost:{port}/{db}";
            var yaml =
$@"  {svc}:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: {user}
      POSTGRES_PASSWORD: {pass}
      POSTGRES_DB: {db}
    ports:
      - ""{port}:5432""
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [""CMD-SHELL"", ""pg_isready -U {user} -d {db}""]
      interval: 5s
      timeout: 5s
      retries: 10
";
            var env = new Dictionary<string, string>
            {
                ["DATABASE_URL"] = conn,
                ["POSTGRES_USER"] = user,
                ["POSTGRES_PASSWORD"] = pass,
                ["POSTGRES_DB"] = db
            };
            return new(DbEngine.Postgres, svc, port, conn, host, env, yaml, new[] { "pgdata" }, true);
        }

        private static DbProvisionResult Mysql(string db, string user, string pass, int port)
        {
            const string svc = "mysql";
            var conn = $"mysql://{user}:{pass}@{svc}:3306/{db}";
            var host = $"mysql://{user}:{pass}@localhost:{port}/{db}";
            var yaml =
$@"  {svc}:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: {db}
      MYSQL_USER: {user}
      MYSQL_PASSWORD: {pass}
      MYSQL_ROOT_PASSWORD: {pass}
    ports:
      - ""{port}:3306""
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: [""CMD"", ""mysqladmin"", ""ping"", ""-h"", ""localhost""]
      interval: 5s
      timeout: 5s
      retries: 10
";
            var env = new Dictionary<string, string>
            {
                ["DATABASE_URL"] = conn,
                ["MYSQL_DATABASE"] = db,
                ["MYSQL_USER"] = user,
                ["MYSQL_PASSWORD"] = pass
            };
            return new(DbEngine.Mysql, svc, port, conn, host, env, yaml, new[] { "mysqldata" }, true);
        }

        private static DbProvisionResult Mongo(string db, string user, string pass, int port)
        {
            const string svc = "mongo";
            var conn = $"mongodb://{user}:{pass}@{svc}:27017/{db}?authSource=admin";
            var host = $"mongodb://{user}:{pass}@localhost:{port}/{db}?authSource=admin";
            var yaml =
$@"  {svc}:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: {user}
      MONGO_INITDB_ROOT_PASSWORD: {pass}
      MONGO_INITDB_DATABASE: {db}
    ports:
      - ""{port}:27017""
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: [""CMD"", ""mongosh"", ""--eval"", ""db.adminCommand('ping')""]
      interval: 5s
      timeout: 5s
      retries: 10
";
            var env = new Dictionary<string, string>
            {
                ["DATABASE_URL"] = conn,
                ["MONGO_URL"] = conn,
                ["MONGO_INITDB_DATABASE"] = db
            };
            return new(DbEngine.Mongo, svc, port, conn, host, env, yaml, new[] { "mongodata" }, true);
        }

        private static DbProvisionResult Redis(int port)
        {
            const string svc = "redis";
            var conn = $"redis://{svc}:6379";
            var host = $"redis://localhost:{port}";
            var yaml =
$@"  {svc}:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - ""{port}:6379""
    volumes:
      - redisdata:/data
    healthcheck:
      test: [""CMD"", ""redis-cli"", ""ping""]
      interval: 5s
      timeout: 5s
      retries: 10
";
            var env = new Dictionary<string, string> { ["REDIS_URL"] = conn };
            return new(DbEngine.Redis, svc, port, conn, host, env, yaml, new[] { "redisdata" }, true);
        }

        private static DbProvisionResult Sqlite(string db)
        {
            // Embedded, file-based — no Docker, always works offline (the fallback strategy).
            var rel = $"data/{db}.db";
            var conn = $"sqlite:///{rel}";
            var env = new Dictionary<string, string>
            {
                ["DATABASE_URL"] = conn,
                ["SQLITE_PATH"] = rel
            };
            return new(DbEngine.Sqlite, "sqlite", 0, conn, conn, env,
                       ComposeServiceYaml: "", Volumes: Array.Empty<string>(), RequiresDocker: false);
        }

        private static string Sanitize(string? name)
        {
            var n = string.IsNullOrWhiteSpace(name) ? "appdb" : name!;
            var cleaned = new string(n.ToLowerInvariant().Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray()).Trim('_');
            return string.IsNullOrEmpty(cleaned) ? "appdb" : cleaned;
        }
    }
}
